### ISSUE TITLE
Consider style enforcement with Prettier

### ISSUE THREAD

**Issue by pswai** [AltSchool/ember-cli-react#13]
With [Prettier](https://github.com/prettier/prettier) we are free from being distracted by code style during code reviews. We can also use ESLint but it still requires some decision making.

If we go with Prettier then it's good if we enforce it with lint-staged and husky as [recommended here](https://github.com/prettier/prettier#option-1-lint-staged). This has the advantage of being IDE/editor -agnostic and requiring zero-setup.

Here's a outline of what we need to do to deploy Prettier:

- [x] Remove `.jshintrc`
- [x] Add Prettier as dependency and enforce it with lint-staged
- [x] Use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) to benefit from editor highlighting
- [x] Make `.editorconfig` compatible with Prettier, if needed

@alexgb what do you think?

**Comment by alexgb** [comment]
Yep, I'm on board with that. Looks good. 👍

**Comment by pswai** [comment]
Sorry was busy recently. Sounds good, I will submit a PR soon
