### ISSUE TITLE
Uncaught Error: Could not find module ember-htmlbars/hooks/get-value

### ISSUE THREAD

**Issue by abhisheksett** [AltSchool/ember-cli-react#18]
When I'm changing the resolver to 'ember-cli-react/resolver', I'm getting error: 'Uncaught Error: Could not find module ember-htmlbars/hooks/get-value' and application is not loading. Anything I'm missing?

**Comment by trailbay** [comment]
@abhisheksett 
I also get the issue. Did you happen to figure out a fix/workaround?

**Comment by abhisheksett** [comment]
I have created a sample application which is working. You can take a look at: https://github.com/abhisheksett/react-in-ember

**Comment by soultrust** [comment]
I'm getting the same error. 

@abhisheksett Can you tell me what is `ember-cli-preact` in your app? I don't know much about Preact. Is that what's pulling React into your project?

**Comment by alexgb** [comment]
@abhisheksett what version of Ember is giving you the resolver error?

**Comment by zendern** [comment]
#20 See this PR , if you are using Ember 3 and higher it may help you.

**Comment by pswai** [comment]
@alexgb This issue can be closed right?

**Comment by alexgb** [comment]
Yep, thanks.
