### ISSUE TITLE
Broken on ember 3.2

### ISSUE THREAD

**Issue by vlascik** [AltSchool/ember-cli-react#21]
Seems that `ember-views/compat/attrs` got removed or moved somewhere else on 3.2 (earlier 3.x perhaps too), loading breaks in ember-cli-react/addon/utils/get-mutable-attributes.js
```
if (isGlimmer) {
  const { MUTABLE_CELL } = Ember.__loader.require('ember-views/compat/attrs');
```
with
```
loader.js:12 Uncaught Error: Could not find module ember-views/compat/attrs
    at missingModule (loader.js:12)
    at internalRequire (loader.js:34)
    at Object.requireModule [as require] (loader.js:88)
    at Module.callback (get-mutable-attributes.js:16)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
```

**Comment by vlascik** [comment]
Yep, that module is now at `ember-views/lib/compat/attrs`.

**Comment by pswai** [comment]
@vlascik Thanks for checking! Do you mind to submit a pull request for this? I don't have permission to merge but that will be very helpful

**Comment by surykumar** [comment]
Hey @pswai , I am having the error  when i use ember-cli-react with ember 3.6                       
"WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
ReactFilter: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md". It was working fine with ember 3.1. Any suggestions ?

**Comment by pswai** [comment]
@surya-zemoso It's very likely that Ember 3.6 dropped support of Broccoli v1, looks like it's time to move away from broccoli-filter to broccoli-funnel. Let me find some time this weekend to fix this :)

**Comment by surykumar** [comment]
Hello @pswai , Any update about the issue?
