### ISSUE TITLE
Uncaught Error: Assertion Failed: A helper named 'say-hi' could not be found

### ISSUE THREAD

**Issue by zlwaterfield** [AltSchool/ember-cli-react#4]
Followed README say-hi example and the component is not being found. Ember is throwing error:

```
Uncaught Error: Assertion Failed: A helper named 'say-hi' could not be found
```

Any ideas what I might be missing?

**Comment by boehlke** [comment]
Hi, I just ran into the same problem. Make sure that you use the Resolver from 'ember-cli-react/resolver' in your app.js.

**Comment by alexgb** [comment]
If you install the addon using `ember install ember-cli-react` the addon blueprint will add the resolver for you. Otherwise, yes, you'll need to do this manually. I should update the Readme.
